collections:
  transcripts:
    output: true


defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: "transcripts"
    values:
      layout: "transcript"